### PR TITLE
Support Debian 9 (stretch)

### PR DESCRIPTION
**Pull request by neomilium**
This patch adds Debian 9 support : under stretch, settings are identical to jessie.

### CODE REVIEW

**Comment by FlorentPoinsaut** [comment]
Hello,

Thank you for this PR.
Could you please add tests? It would be great :-)

Thank you.
Regards,

**Comment by neomilium** [comment]
PR #14 should be applied to pass all tests.

**Comment by FlorentPoinsaut** [comment]
Hello,

Thank you for your hard work.
I fixed this in the develop branch and I will publish a new release soon.

Regards,

**Comment by neomilium** [comment]
Up?

**Comment by FlorentPoinsaut** [comment]
Hi,
I merged your work on a new repository: https://github.com/solution-libre/puppet-gitolite
You can find the new module here: https://forge.puppet.com/soli/gitolite
Regards,

**Pull request closed without merging**
